### ISSUE TITLE
Hiding and showing text

### ISSUE THREAD

**Issue by Sebastian-henn** [OfficeDev/Word-Add-in-Tutorial#3]
Great tutorial with some very handy examples, thanks for sharing!

I was wondering if there is a way to toggle a section of text through an Add-In using the OfficeJS API. The approach I would take would be to mark the text within a section as "hidden" (ie right click on text -> font -> hidden), which can be accessed through [Office VBA](https://docs.microsoft.com/en-us/office/vba/api/word.font.hidden), however I can't seem to find this property in JS. 

Am I just missing something obvious? Or is there an alternate approach one could take? I don't want to simply delete the section...

**Comment by Rick-Kirkham** [comment]
Thanks for your interest in Word Add-ins. The issues for this repo are intended to track errors in the tutorial itself. For technical questions like this, we suggest that you raise it on StackOverflow where the entire community will benefit from the answers that you get. Be sure to tag the question `office-js`.
